# Generated by Django 3.2.4 on 2021-06-25 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='post',
            name='short_name',
            field=models.CharField(default=datetime.datetime(2021, 6, 25, 15, 49, 14, 625159, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
