# Generated by Django 3.2.4 on 2021-06-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_overview2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview2',
        ),
    ]
